'use strict';

/**
 * CipherLink application-layer protocol.
 *
 * Transport pipeline (unchanged since Phase 1 - do not collapse these
 * layers into each other):
 *
 *   TCP byte stream -> LineBuffer -> JSON decode -> protocol validation
 *   -> message handling -> security layer (src/security/)
 *
 * Framing: one JSON object per line, separated by "\n". LineBuffer only
 * buffers and splits bytes; it has no knowledge of message content and
 * must stay that way.
 *
 * ---------------------------------------------------------------------
 * Message types
 * ---------------------------------------------------------------------
 *   CHAT              plaintext chat text (still plaintext in this phase)
 *   SYSTEM / ERROR    server-originated status / rejection notices
 *   HELLO             client announces its two PUBLIC keys
 *   KEY_EXCHANGE      initiator sends the RSA-OAEP-wrapped session key + signature
 *   KEY_EXCHANGE_ACK  responder confirms receipt, signed
 *   REKEY, REKEY_ACK  reserved for a later phase
 *
 * ---------------------------------------------------------------------
 * Handshake schemas (version is REQUIRED for these three types)
 * ---------------------------------------------------------------------
 *   HELLO            { type, version, sender, encryptionPublicKey, signingPublicKey }
 *   KEY_EXCHANGE     { type, version, sender, recipient, sessionId, encryptedSessionKey, signature }
 *   KEY_EXCHANGE_ACK { type, version, sender, recipient, sessionId, signature }
 *
 *   - Public keys are the exact SPKI PEM strings produced by src/crypto/keys.js.
 *   - sessionId is 32 lowercase hex characters (128 random bits).
 *   - encryptedSessionKey and signature are canonical standard base64 of raw bytes.
 *   - Handshake messages have an exact field allow-list: unknown fields are
 *     rejected, so nothing unsigned can ride along in them.
 *   - Any handshake message containing private-key material is rejected.
 *
 * ---------------------------------------------------------------------
 * Field ownership
 * ---------------------------------------------------------------------
 *   type, version  - set by the author; version checked by every receiver.
 *   sender         - HELLO/KEY_EXCHANGE/ACK: set by the sending client. The
 *                    server REJECTS a message whose sender is not the
 *                    connection's assigned identity (it does not rewrite it,
 *                    because sender is covered by the signature). For CHAT the
 *                    server still stamps sender itself (CHAT is not signed).
 *   recipient      - set by the sending client, signed. The server only
 *                    checks it names the other client; it never changes it.
 *   sessionId, encryptedSessionKey, signature
 *                  - generated by the initiating/responding CLIENT
 *                    (src/security/handshake.js). The server never creates
 *                    or alters them.
 *
 * Still reserved and NOT implemented (later phases): sequence, timestamp,
 * nonce, ciphertext, authTag on CHAT.
 *
 * Validation here is STRUCTURAL. It checks shapes, sizes and that public
 * keys parse as RSA keys of an acceptable size. Verifying signatures and
 * decrypting are done by the security layer, never by the server.
 */

const { importPublicKey, MIN_MODULUS_LENGTH } = require('../crypto/keys');

const PROTOCOL_VERSION = 1;
const SUPPORTED_VERSIONS = Object.freeze([1]);

const MESSAGE_TYPES = Object.freeze({
  HELLO: 'HELLO',
  CHAT: 'CHAT',
  SYSTEM: 'SYSTEM',
  ERROR: 'ERROR',
  KEY_EXCHANGE: 'KEY_EXCHANGE',
  KEY_EXCHANGE_ACK: 'KEY_EXCHANGE_ACK',
  // Reserved for a future phase - vocabulary only, no behavior yet.
  REKEY: 'REKEY',
  REKEY_ACK: 'REKEY_ACK',
});

/** Types with a validated schema today. */
const IMPLEMENTED_TYPES = Object.freeze([
  MESSAGE_TYPES.HELLO,
  MESSAGE_TYPES.CHAT,
  MESSAGE_TYPES.SYSTEM,
  MESSAGE_TYPES.ERROR,
  MESSAGE_TYPES.KEY_EXCHANGE,
  MESSAGE_TYPES.KEY_EXCHANGE_ACK,
]);

/** Recognized vocabulary reserved for later phases; rejected if received today. */
const RESERVED_TYPES = Object.freeze([
  MESSAGE_TYPES.REKEY,
  MESSAGE_TYPES.REKEY_ACK,
]);

/** Client-to-client handshake messages; the server relays these verbatim. */
const HANDSHAKE_TYPES = Object.freeze([
  MESSAGE_TYPES.HELLO,
  MESSAGE_TYPES.KEY_EXCHANGE,
  MESSAGE_TYPES.KEY_EXCHANGE_ACK,
]);

/** Structured presence notices carried in SYSTEM messages (the text stays human-readable). */
const PEER_EVENTS = Object.freeze({
  PEER_JOINED: 'PEER_JOINED',
  PEER_LEFT: 'PEER_LEFT',
});

const HANDSHAKE_FIELDS = Object.freeze({
  [MESSAGE_TYPES.HELLO]: ['type', 'version', 'sender', 'encryptionPublicKey', 'signingPublicKey'],
  [MESSAGE_TYPES.KEY_EXCHANGE]: ['type', 'version', 'sender', 'recipient', 'sessionId', 'encryptedSessionKey', 'signature'],
  [MESSAGE_TYPES.KEY_EXCHANGE_ACK]: ['type', 'version', 'sender', 'recipient', 'sessionId', 'signature'],
});

const MAX_IDENTITY_LENGTH = 64;
const MAX_PEM_LENGTH = 4096;
const SESSION_ID_PATTERN = /^[0-9a-f]{32}$/;
// RSA outputs (OAEP ciphertext, PSS signature) are one modulus long: 384 bytes for
// 3072-bit keys, up to 1024 bytes for 8192-bit keys.
const MIN_RSA_OUTPUT_BYTES = MIN_MODULUS_LENGTH / 8;
const MAX_RSA_OUTPUT_BYTES = 1024;

/**
 * Maximum size of ONE frame (one message line, excluding its "\n"), in UTF-8
 * bytes. Every real message is far smaller (a HELLO with two 3072-bit public
 * keys is ~1.5 KB, KEY_EXCHANGE ~1.4 KB); 64 KiB leaves ample room for chat
 * text while bounding how much a peer can make us buffer.
 */
const MAX_FRAME_SIZE = 64 * 1024;

/** Thrown by LineBuffer when a frame exceeds the maximum size. The connection should be closed. */
class FrameTooLargeError extends Error {
  constructor(maxFrameSize) {
    super(`Frame exceeds the maximum size of ${maxFrameSize} bytes.`);
    this.name = 'FrameTooLargeError';
    this.maxFrameSize = maxFrameSize;
  }
}

/**
 * Accumulates raw socket bytes and yields complete, newline-delimited lines.
 * Never buffers more than one maximum-size frame (plus the chunk in hand):
 * a frame that is too large - whether it already ended in "\n" or is still
 * growing without one - throws FrameTooLargeError and the buffer is emptied.
 * After that error the stream position is untrustworthy, so callers close
 * the connection instead of trying to resynchronize.
 */
class LineBuffer {
  constructor(maxFrameSize = MAX_FRAME_SIZE) {
    this._buffer = '';
    this._maxFrameSize = maxFrameSize;
  }

  /**
   * @param {string} chunk newly received text (already utf8-decoded)
   * @returns {string[]} zero or more complete lines (without the trailing "\n")
   * @throws {FrameTooLargeError}
   */
  append(chunk) {
    this._buffer += chunk;
    const lines = this._buffer.split('\n');
    // The last element is either '' (chunk ended exactly on a newline)
    // or an incomplete line still waiting for more data; keep it buffered.
    const partial = lines.pop();
    if (Buffer.byteLength(partial, 'utf8') > this._maxFrameSize
      || lines.some((line) => Buffer.byteLength(line, 'utf8') > this._maxFrameSize)) {
      this._buffer = '';
      throw new FrameTooLargeError(this._maxFrameSize);
    }
    this._buffer = partial;
    return lines;
  }
}

function encode(messageObj) {
  return JSON.stringify(messageObj) + '\n';
}

/** @throws {SyntaxError} if the line is not valid JSON */
function decode(line) {
  return JSON.parse(line);
}

function createHelloMessage(sender, encryptionPublicKey, signingPublicKey, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.HELLO, version, sender, encryptionPublicKey, signingPublicKey };
}

function createKeyExchangeMessage({ sender, recipient, sessionId, encryptedSessionKey, signature }, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.KEY_EXCHANGE, version, sender, recipient, sessionId, encryptedSessionKey, signature };
}

function createKeyExchangeAckMessage({ sender, recipient, sessionId, signature }, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.KEY_EXCHANGE_ACK, version, sender, recipient, sessionId, signature };
}

function createChatMessage(sender, text, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.CHAT, version, sender, text };
}

function createSystemMessage(text, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.SYSTEM, version, text };
}

/** SYSTEM message that also carries a machine-readable presence event. */
function createPeerEventMessage(event, peer, text, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.SYSTEM, version, text, event, peer };
}

function createErrorMessage(text, version = PROTOCOL_VERSION) {
  return { type: MESSAGE_TYPES.ERROR, version, text };
}

function invalid(reason) {
  return { valid: false, reason };
}

function isIdentityString(value) {
  return typeof value === 'string' && value.trim() !== '' && value.length <= MAX_IDENTITY_LENGTH;
}

/** True only for canonical standard base64 (so one byte string has exactly one text form). */
function isCanonicalBase64(value) {
  if (typeof value !== 'string' || value.length === 0 || value.length % 4 !== 0) return false;
  if (!/^[A-Za-z0-9+/]+={0,2}$/.test(value)) return false;
  return Buffer.from(value, 'base64').toString('base64') === value;
}

function isRsaOutputField(value) {
  if (!isCanonicalBase64(value)) return false;
  const bytes = Buffer.from(value, 'base64').length;
  return bytes >= MIN_RSA_OUTPUT_BYTES && bytes <= MAX_RSA_OUTPUT_BYTES;
}

function containsPrivateKeyMaterial(msg) {
  return Object.entries(msg).some(
    ([field, value]) => /private/i.test(field) || (typeof value === 'string' && /PRIVATE KEY/.test(value))
  );
}

/** Parses a PEM public-key field; returns { key } or { reason }. */
function parsePublicKeyField(msg, field) {
  const pem = msg[field];
  if (typeof pem !== 'string' || pem.length === 0 || pem.length > MAX_PEM_LENGTH) {
    return { reason: `${msg.type} "${field}" must be a PEM public key string.` };
  }
  try {
    return { key: importPublicKey(pem) };
  } catch (err) {
    return { reason: `${msg.type} "${field}" is not a valid RSA public key (SPKI PEM, at least ${MIN_MODULUS_LENGTH} bits).` };
  }
}

function validateHandshakeMessage(msg) {
  const type = msg.type;

  if (containsPrivateKeyMaterial(msg)) {
    return invalid(`${type} message must not contain private key material.`);
  }
  if (msg.version === undefined) {
    return invalid(`${type} message requires "version".`);
  }
  if (!SUPPORTED_VERSIONS.includes(msg.version)) {
    return invalid(`Unsupported protocol version: ${String(msg.version).slice(0, 32)}`);
  }

  const allowed = HANDSHAKE_FIELDS[type];
  for (const field of Object.keys(msg)) {
    if (!allowed.includes(field)) {
      return invalid(`${type} message contains unexpected field "${field}".`);
    }
  }
  for (const field of allowed) {
    if (msg[field] === undefined) {
      return invalid(`${type} message requires "${field}".`);
    }
  }

  if (!isIdentityString(msg.sender)) {
    return invalid(`${type} "sender" must be a non-empty string of at most ${MAX_IDENTITY_LENGTH} characters.`);
  }

  if (type === MESSAGE_TYPES.HELLO) {
    const enc = parsePublicKeyField(msg, 'encryptionPublicKey');
    if (!enc.key) return invalid(enc.reason);
    const sig = parsePublicKeyField(msg, 'signingPublicKey');
    if (!sig.key) return invalid(sig.reason);
    if (enc.key.equals(sig.key)) {
      return invalid('HELLO must advertise two different keys: encryption and signing keys must not be reused.');
    }
    return { valid: true };
  }

  if (!isIdentityString(msg.recipient)) {
    return invalid(`${type} "recipient" must be a non-empty string of at most ${MAX_IDENTITY_LENGTH} characters.`);
  }
  if (msg.recipient === msg.sender) {
    return invalid(`${type} "recipient" must differ from "sender".`);
  }
  if (typeof msg.sessionId !== 'string' || !SESSION_ID_PATTERN.test(msg.sessionId)) {
    return invalid(`${type} "sessionId" must be 32 lowercase hex characters.`);
  }
  if (type === MESSAGE_TYPES.KEY_EXCHANGE && !isRsaOutputField(msg.encryptedSessionKey)) {
    return invalid('KEY_EXCHANGE "encryptedSessionKey" must be canonical base64 of an RSA-sized value.');
  }
  if (!isRsaOutputField(msg.signature)) {
    return invalid(`${type} "signature" must be canonical base64 of an RSA-sized value.`);
  }
  return { valid: true };
}

/**
 * Structural validation for any CipherLink protocol message. Checks shape
 * only (object, known type, supported version, required fields and their
 * basic types, key/encoding well-formedness). It does not verify
 * signatures or decrypt anything.
 *
 * @returns {{ valid: true } | { valid: false, reason: string }}
 */
function validateMessage(msg) {
  if (!msg || typeof msg !== 'object' || Array.isArray(msg)) {
    return invalid('Message must be a JSON object.');
  }

  if (typeof msg.type !== 'string' || msg.type.trim() === '') {
    return invalid('Message is missing a "type" field.');
  }

  if (RESERVED_TYPES.includes(msg.type)) {
    return invalid(`Message type "${msg.type}" is reserved for a future CipherLink phase and is not supported yet.`);
  }

  if (!IMPLEMENTED_TYPES.includes(msg.type)) {
    return invalid(`Unsupported message type: ${msg.type}`);
  }

  if (HANDSHAKE_TYPES.includes(msg.type)) {
    return validateHandshakeMessage(msg);
  }

  if (msg.version !== undefined && !SUPPORTED_VERSIONS.includes(msg.version)) {
    return invalid(`Unsupported protocol version: ${msg.version}`);
  }

  switch (msg.type) {
    case MESSAGE_TYPES.CHAT:
      if (typeof msg.text !== 'string') {
        return invalid('CHAT message requires "text" to be a string.');
      }
      if (msg.text.trim() === '') {
        return invalid('CHAT message requires non-empty "text".');
      }
      break;

    case MESSAGE_TYPES.SYSTEM:
    case MESSAGE_TYPES.ERROR:
      if (typeof msg.text !== 'string' || msg.text.trim() === '') {
        return invalid(`${msg.type} message requires non-empty "text".`);
      }
      if (msg.type === MESSAGE_TYPES.SYSTEM && msg.event !== undefined) {
        if (!Object.values(PEER_EVENTS).includes(msg.event)) {
          return invalid(`Unknown SYSTEM event: ${String(msg.event).slice(0, 32)}`);
        }
        if (!isIdentityString(msg.peer)) {
          return invalid('SYSTEM event requires a non-empty "peer".');
        }
      }
      break;
  }

  return { valid: true };
}

module.exports = {
  PROTOCOL_VERSION,
  SUPPORTED_VERSIONS,
  MESSAGE_TYPES,
  IMPLEMENTED_TYPES,
  RESERVED_TYPES,
  HANDSHAKE_TYPES,
  PEER_EVENTS,
  MAX_FRAME_SIZE,
  FrameTooLargeError,
  LineBuffer,
  encode,
  decode,
  createHelloMessage,
  createKeyExchangeMessage,
  createKeyExchangeAckMessage,
  createChatMessage,
  createSystemMessage,
  createPeerEventMessage,
  createErrorMessage,
  validateMessage,
};
